-- Cliente
CREATE TABLE SA1010 (
  A1_FILIAL VARCHAR(2),
  A1_COD VARCHAR(6),
  A1_NOME VARCHAR(60),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SA1010 PRIMARY KEY (A1_FILIAL, A1_COD)
);

-- Tipo de Entrada e Saída
CREATE TABLE SF4010 (
  F4_FILIAL VARCHAR(2),
  F4_CODIGO VARCHAR(3),
  F4_ESTOQUE VARCHAR(1),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SF4010 PRIMARY KEY (F4_FILIAL, F4_CODIGO)
);

-- Condição de Pagamento
CREATE TABLE SE4010 (
  E4_FILIAL VARCHAR(2),
  E4_CODIGO VARCHAR(3),
  E4_COND VARCHAR(3),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SE4010 PRIMARY KEY (E4_FILIAL, E4_CODIGO)
);

-- Pedido de Venda
CREATE TABLE SC5010 (
  C5_FILIAL VARCHAR(2),
  C5_NUM VARCHAR(6),
  C5_VEND1 VARCHAR(6),
  C5_OBSPED VARCHAR(60),
  C5_PREVIST VARCHAR(8),
  C5_XST05 VARCHAR(2),
  C5_XFRET VARCHAR(1),
  C5_XFLAG VARCHAR(3),
  C5_XSEP VARCHAR(1),
  C5_NOTA VARCHAR(9),
  C5_CLIENT VARCHAR(6),
  C5_TIPO VARCHAR(1),
  C5_CONDPAG VARCHAR(3),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SC5010 PRIMARY KEY (C5_FILIAL, C5_NUM),
  CONSTRAINT FK_SC5_SE4 FOREIGN KEY (C5_FILIAL, C5_CONDPAG) REFERENCES SE4010 (E4_FILIAL, E4_CODIGO),
  CONSTRAINT FK_SC5_SA1 FOREIGN KEY (C5_FILIAL, C5_CLIENT) REFERENCES SA1010 (A1_FILIAL, A1_COD)
);

-- Item Pedido de Venda
CREATE TABLE SC6010 (
  C6_FILIAL VARCHAR(2),
  C6_NUM VARCHAR(6),
  C6_ITEM VARCHAR(2),
  C6_PRODUTO VARCHAR(15),
  C6_LOCAL VARCHAR(2),
  C6_BLQ VARCHAR(1),
  C6_QTDVEN NUMERIC(10,4),
  C6_QTDENT NUMERIC(10,4),
  C6_PRCVEN NUMERIC(10,2),
  C6_XQTD05 NUMERIC(10,4),
  C6_VALOR NUMERIC(10,2),
  C6_XFLAG VARCHAR(3),
  C6_TES VARCHAR(3),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SC6010 PRIMARY KEY (C6_FILIAL, C6_NUM, C6_ITEM),
  CONSTRAINT FK_SC6_SC5 FOREIGN KEY (C6_FILIAL, C6_NUM) REFERENCES SC5010 (C5_FILIAL, C5_NUM),
  CONSTRAINT FK_SC6_SF4 FOREIGN KEY (C6_FILIAL, C6_TES) REFERENCES SF4010 (F4_FILIAL, F4_CODIGO)
);

-- Item Pedido Venda Liberado
CREATE TABLE SC9010 (
  C9_FILIAL VARCHAR(2),
  C9_PEDIDO VARCHAR(6),
  C9_ITEM VARCHAR(2),
  C9_SEQUEN VARCHAR(2),
  C9_PRODUTO VARCHAR(15),
  C9_NFISCAL VARCHAR(9),
  C9_XLIST VARCHAR(3),
  C9_LOCAL VARCHAR(2),
  C9_BLCRED VARCHAR(2),
  D_E_L_E_T_ VARCHAR(1),
  CONSTRAINT PK_SC9010 PRIMARY KEY (C9_FILIAL, C9_PEDIDO, C9_ITEM, C9_SEQUEN),
  CONSTRAINT FK_SC9_SC6 FOREIGN KEY (C9_FILIAL, C9_PEDIDO, C9_ITEM) REFERENCES SC6010 (C6_FILIAL, C6_NUM, C6_ITEM)
);
