Vagrant.configure("2") do |config|

  # Official Operating System from Hashicorp (Ubuntu Server)
  config.vm.box = "hashicorp/precise64"

  # IP to access the virtual machine
  config.vm.network "private_network", ip: "192.168.33.10"

  # Ensure the default folder sync but only from host to guest
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # Disables the random Vagrant SSH key generation using the default insecure key
  config.ssh.insert_key = false

  # Installing what we need for the example (simple script without interaction)
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install default-jdk -y
    apt-get install tomcat7 -y
  SHELL
end