# -*- mode: ruby -*- 
# vi: set ft=ruby : 

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "database.sh"

  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

  config.vm.provider :virtualbox do |vb|
    vb.name = "cte-postgresql"
    vb.memory = 1536
    vb.cpus = 2
  end
end
